name: video_seal
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10

  - pytorch::pytorch==2.5.1
  - pytorch::pytorch-cuda==12.4
  - pytorch::torchvision==0.20.1
  # conda-forge miss cuda_124 https://anaconda.org/conda-forge/torchaudio/files?version=2.5.1&sort=basename&sort_order=desc
  - pytorch::torchaudio==2.5.1

  - pytorch::ffmpeg==4.3

  - pip:
    - jupyter==1.1.1
    - audioseal==0.1.4
    - -r ./videoseal/requirements.txt
