name: video_seal
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10

  - pytorch::pytorch==2.5.1
  - pytorch::pytorch-cuda==12.4
  # conda-forge miss cuda_124 https://anaconda.org/conda-forge/torchaudio/files?version=2.5.1&sort=basename&sort_order=desc
  - pytorch::torchaudio==2.5.1
  # pip package to resolve dependencies on older versions of ffmpeg
  # - pytorch::torchvision==0.20.1
  # conda-forge support encoder 'libx264'
  - conda-forge::ffmpeg==7.1.0

  - pip:
    - torch==2.5.1
    - jupyter==1.1.1
    - matplotlib==3.10.0
    - gradio==5.8.0
    - pydantic==2.10.5
    - audioseal==0.1.4
    - torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cu124
    - -r ./videoseal/requirements.txt
