
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir \
    jupyter==1.1.1 \
    pydantic==2.10.5 \
    gradio==5.8.0 \
    matplotlib==3.10.0 \
    audioseal==0.1.4

COPY ./videoseal/requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./videoseal /app

COPY ./gradio /workspace/gradio

EXPOSE 8888
EXPOSE 7860

VOLUME /root/.cache

ENV APP_PATH=/app
ENV GRADIO_SERVER_NAME="0.0.0.0"

CMD ["jupyter", "notebook", "--allow-root", "--ip", "0.0.0.0"]
