

services:
  video-seal:
    image: xiaoyao9184/video-seal:main
    container_name: video-seal-nb
    environment:
      - HF_HUB_OFFLINE=true
    ports:
      - "8888:8888"
    volumes:
      - ./../../cache:/root/.cache
